// src/components/Ridunews.tsx
import { useApi } from "#/lib/openapi";
import { Link } from "@tanstack/react-router";
import {
	Bell,
	Eye,
	Gift,
	Languages,
	ShoppingCartIcon,
	UserRound,
} from "lucide-react";
import { useEffect, useState } from "react";
import { FaDiscord, FaGithub } from "react-icons/fa";

type Features = {
	icon: React.ReactNode;
	label: string;
};

const features: Features[] = [
	{
		icon: <Eye size={18} />,
		label: "Detection",
	},
	{
		icon: <UserRound size={18} />,
		label: "Roles",
	},
	{
		icon: <Languages size={18} />,
		label: "Language",
	},
	{
		icon: <Gift size={18} />,
		label: "Giveaways",
	},
	{
		icon: <Bell size={18} />,
		label: "Notification",
	},
];

const socialLinks = [
	{
		label: "Discord",
		href: "https://discord.gg/DBNATxA6Jx",
		icon: <FaDiscord className="text-[#E5D2C5]" size={20} />,
	},
	{
		label: "GitHub",
		href: "https://github.com/BangbooBot",
		icon: <FaGithub className="text-[#E5D2C5]" size={20} />,
	},
]

const botStatus = {
	serverCount: 0,
	commandCount: 0,
};

const api = useApi();

export function Ridunews() {
	const [status, setStatus] = useState(botStatus);
	useEffect(() => {
		api.GET("/status").then((res) => {
			if (res.data) {
				setStatus({
					serverCount: res.data.serverCount as number,
					commandCount: res.data.commandsCount as number,
				});
			}
		});
	}, []);

	return (
		<div className="max-w-xl flex flex-col gap-y-2 p-2 rounded-md bg-[#E5D2C5] border border-white/10 shadow-lg shadow-white/10">
			<section className="w-fit px-4 py-1 flex justify-between items-center rounded-full bg-[#2B312B]">
				<span className="text-[12px] font-bold text-[#E5D2C5]">
					Ridu Newsletter
				</span>
			</section>

			<section className="w-full px-2 py-1 flex justify-between items-center rounded-sm bg-[#2B312B]">
				<span className="text-4xl font-bold text-[#E5D2C5]">DISCORD BOT</span>
			</section>

			<section className="w-full p-2 rounded-sm overflow-hidden bg-[#2B312B]">
				<div className="mx-auto grid grid-cols-2 max-[500px]:grid-cols-1 max-[500px]:justify-items-center gap-x-4 gap-y-2">
					<div className="w-full flex justify-center">
						<div className="w-fit flex flex-col justify-center items-center rounded-sm border-4 border-[#E5D2C5]">
							<img
								src="/img/brand.png"
								alt="Bangboo Logo"
								width={250}
								height={250}
							/>
							<div className="flex justify-center items-center py-2 w-full bg-[#E5D2C5]">
								<p className="font-extrabold text-lg sm:text-xl text-[#2B312B] tracking-wide">
									ENN ENNEN
								</p>
							</div>
						</div>
					</div>

					<div className="max-w-[250px] flex flex-col gap-y-2 ">
						<h1 className="text-lg font-extrabold text-[#E5D2C5]">
							SMALL BODY, BIG HELPER!
						</h1>
						<p className="text-base font-medium text-justify text-[#E5D2C5]">
							All servers need an autonomous bunny to guide them through the darkest corners.
						</p>
					</div>
				</div>
			</section>

			<section className="w-full p-4 rounded-sm overflow-hidden bg-[#2B312B]">
				<div className="flex flex-col w-full justify-between items-center">
					<div className="flex flex-wrap w-full gap-4 items-center justify-center">
						{features.map((feature, index) => (
							<div
								key={index}
								className="flex flex-col items-center bg-[#E5D2C5] px-4 py-2 rounded-sm min-w-[110px] flex-shrink-0"
							>
								<span className="text-[#2B312B]">{feature.icon}</span>
								<span className="text-[#2B312B] font-medium text-sm">
									{feature.label}
								</span>
							</div>
						))}
					</div>

					<div className="flex flex-wrap justify-center items-center gap-8 pt-5 w-full mt-2">
						<div className="flex flex-col items-center gap-y-2">
							<div className="min-w-[80px] h-10 px-3 rounded-sm flex justify-center items-center bg-[#E5D2C5] text-base font-extrabold text-[#2B312B] shadow-inner">
								{status.serverCount}+
							</div>
							<h5 className="text-sm font-bold text-[#E5D2C5]">Guilds</h5>
						</div>
						<div className="flex flex-col items-center gap-y-2">
							<div className="min-w-[80px] h-10 px-3 rounded-sm flex justify-center items-center bg-[#E5D2C5] text-base font-extrabold text-[#2B312B] shadow-inner">
								{status.commandCount}+
							</div>
							<h5 className="text-sm font-bold text-[#E5D2C5]">Commands</h5>
						</div>
					</div>
				</div>
			</section>

			<section className="w-full flex justify-between items-center py-4 px-2 rounded-sm">
				<div>
					<Link
						className="text-[#E5D2C5] bg-[#2B312B] font-medium px-4 py-2 rounded-md hover:brightness-125 transition-all"
						to={"/"}
					>
						Invite
					</Link>
				</div>

				<div className="flex gap-x-2">
					{socialLinks.map((link, index) => (
						<a
							key={index}
							href={link.href}
							target="_blank"
							rel="noopener noreferrer"
							className="text-[#E5D2C5] bg-[#2B312B] font-medium p-2 rounded-md flex items-center justify-center hover:brightness-125 transition-all"
						>
							{link.icon}
						</a>
					))}
				</div>
			</section>
		</div>
	);
}

// app/components/Ridunews.vue
<script setup lang="ts">
const { data: botStatus, status, error, refresh } = useAsyncData("spaces", async () => {
    const api = useFastify()
    const { data, error, response } = await api.GET("/")
    return data;
});
</script>

<template>
    <UCard variant="subtle" class="max-w-[480px] w-full" :ui="{
        root: 'rounded-xs bg-zinc-100 dark:bg-zinc-900 shadow-xl ring-1 ring-zinc-200 dark:ring-zinc-800',
        body: 'p-4 sm:p-6',
        header: 'p-4 sm:px-6 sm:pt-6 sm:pb-2 border-none',
        footer: 'p-4 sm:px-6 sm:pb-6 sm:pt-2 border-none'
    }">
        <template #header>
            <section class="flex flex-col items-start gap-3 w-full">
                <div class="bg-zinc-200 dark:bg-zinc-800 px-4 py-1.5 rounded-full flex items-center shadow-inner">
                    <span class="text-xs font-bold tracking-wider text-zinc-700 dark:text-zinc-300 uppercase">Ridu
                        News</span>
                </div>
                <div
                    class="w-full bg-zinc-200 dark:bg-zinc-800/80 px-4 py-3 rounded-sm flex items-center border border-zinc-300 dark:border-zinc-700">
                    <h1 class="text-2xl sm:text-3xl font-black tracking-tight text-zinc-900 dark:text-zinc-100">BANGBOO
                        BOT</h1>
                </div>
            </section>
        </template>

        <div class="flex flex-col gap-y-4">
            <!-- Hero Info Card Section -->
            <section
                class="bg-zinc-200 dark:bg-zinc-800 px-4 py-5 grid grid-cols-1 sm:grid-cols-2 gap-6 rounded-sm border border-zinc-300 dark:border-zinc-700/50">
                <div class="w-full flex justify-center items-center">
                    <div
                        class="relative w-full max-w-[180px] aspect-square flex justify-center items-center rounded-sm border-4 border-zinc-50 dark:border-zinc-700 bg-zinc-100 dark:bg-zinc-900 shadow-inner overflow-hidden isolate">
                        <NuxtImg src="/images/bangboo/18.png" class="h-[85%] object-contain relative -top-3"
                            alt="Bangboo" />
                        <div
                            class="absolute bottom-0 w-full bg-zinc-200/90 dark:bg-zinc-800/95 backdrop-blur py-2 flex justify-center items-center border-t border-zinc-300 dark:border-zinc-700 rounded-b-sm z-10">
                            <p class="font-extrabold text-lg sm:text-xl text-zinc-900 dark:text-zinc-100 tracking-wide">
                                ENN ENNEN
                            </p>
                        </div>
                    </div>
                </div>

                <div class="w-full flex flex-col justify-center items-start gap-y-3">
                    <h1
                        class="font-[Anton] text-xl sm:text-[22px] leading-tight text-zinc-900 dark:text-zinc-50 uppercase tracking-wide">
                        Small body, big helper!
                    </h1>
                    <p class="font-medium text-sm text-zinc-700 dark:text-zinc-300 text-justify leading-relaxed">
                        Todo servidor precisa de um coelho autônomo para guiá-lo até mesmo nos cantos mais escuros.
                        Moderação,
                        Comandos divertidos, Notificação, Segurança e muito mais!
                    </p>
                </div>
            </section>

            <!-- Features & Stats Section -->
            <section
                class="bg-zinc-200 dark:bg-zinc-800 py-6 px-4 rounded-sm flex flex-col items-center gap-6 border border-zinc-300 dark:border-zinc-700/50">
                <div class="flex flex-wrap justify-center gap-4 sm:gap-6 w-full">
                    <div class="flex flex-col items-center gap-y-2 min-w-[70px]">
                        <UIcon name="i-lucide-scan-eye" class="w-8 h-8 opacity-80 dark:opacity-100" />
                        <h5 class="text-xs sm:text-sm font-bold text-zinc-700 dark:text-zinc-300 text-center">Moderação
                        </h5>
                    </div>
                    <div class="flex flex-col items-center gap-y-2 min-w-[70px]">
                        <UIcon name="i-lucide-user-round-key" class="w-8 h-8 opacity-80 dark:opacity-100" />
                        <h5 class="text-xs sm:text-sm font-bold text-zinc-700 dark:text-zinc-300 text-center">Cargos
                        </h5>
                    </div>
                    <div class="flex flex-col items-center gap-y-2 min-w-[70px]">
                        <UIcon name="i-lucide-languages" class="w-8 h-8 opacity-80 dark:opacity-100" />
                        <h5 class="text-xs sm:text-sm font-bold text-zinc-700 dark:text-zinc-300 text-center">Idioma
                        </h5>
                    </div>
                    <div class="flex flex-col items-center gap-y-2 min-w-[70px]">
                        <UIcon name="i-lucide-gift" class="w-8 h-8 opacity-80 dark:opacity-100" />
                        <h5 class="text-xs sm:text-sm font-bold text-zinc-700 dark:text-zinc-300 text-center">Sorteios
                        </h5>
                    </div>
                    <div class="flex flex-col items-center gap-y-2 min-w-[70px]">
                        <UIcon name="i-lucide-twitch" class="w-8 h-8 opacity-80 dark:opacity-100" />
                        <h5 class="text-xs sm:text-sm font-bold text-zinc-700 dark:text-zinc-300 text-center">Twitch
                        </h5>
                    </div>
                </div>

                <div
                    class="flex flex-wrap justify-center items-center gap-8 border-t border-zinc-300 dark:border-zinc-700 pt-5 w-full mt-2">
                    <div class="flex flex-col items-center gap-y-2">
                        <div
                            class="min-w-[80px] h-10 px-3 rounded-xl flex justify-center items-center bg-zinc-300 dark:bg-zinc-700 text-base font-extrabold text-zinc-900 dark:text-zinc-100 shadow-inner border border-zinc-400/50 dark:border-zinc-600/50">
                            {{ botStatus ? `${botStatus.guilds}` : "..." }}+</div>
                        <h5 class="text-sm font-bold text-zinc-700 dark:text-zinc-300">Servidores</h5>
                    </div>
                    <div class="flex flex-col items-center gap-y-2">
                        <div
                            class="min-w-[80px] h-10 px-3 rounded-xl flex justify-center items-center bg-zinc-300 dark:bg-zinc-700 text-base font-extrabold text-zinc-900 dark:text-zinc-100 shadow-inner border border-zinc-400/50 dark:border-zinc-600/50">
                            {{ botStatus ? `${botStatus.commands}` : "..." }}+</div>
                        <h5 class="text-sm font-bold text-zinc-700 dark:text-zinc-300">Comandos</h5>
                    </div>
                </div>
            </section>
        </div>

        <template #footer>
            <section class="flex flex-col sm:flex-row gap-4 justify-between items-center w-full">
                <UButton target="_blank" to="https://discord.gg/your-invite-link" size="lg" color="neutral"
                    variant="solid" aria-label="Discord" class="rounded-full">
                    Convide-me agora
                </UButton>
                <div class="flex items-center gap-2">
                    <UButton target="_blank" to="https://discord.gg/your-invite-link" icon="i-simple-icons-discord"
                        size="lg" color="neutral" variant="ghost" aria-label="Discord"
                        class="rounded-full hover:bg-zinc-200 dark:hover:bg-zinc-800" />
                    <UButton target="_blank" to="https://github.com/BangbooBot" icon="i-simple-icons-github" size="lg"
                        color="neutral" variant="ghost" aria-label="GitHub"
                        class="rounded-full hover:bg-zinc-200 dark:hover:bg-zinc-800" />
                </div>
            </section>
        </template>
    </UCard>
</template>
